services:
  rabbit-1:
    image: rabbitmq:3-management
    container_name: rabbit-1
    hostname: rabbit-1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    command: >
        sh -c "
          rabbitmq-server -detached &&
          rabbitmq-plugins enable rabbitmq_management &&
          tail -f /dev/null
        "
    networks:
      - rabbitmq_net

  rabbit-2:
    image: rabbitmq:3-management
    container_name: rabbit-2
    hostname: rabbit-2
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    command: >
        sh -c "
          rabbitmq-server -detached &&
          sleep 10 &&
          rabbitmqctl stop_app &&
          rabbitmqctl reset &&
          rabbitmqctl join_cluster rabbit@rabbit-1 &&
          rabbitmqctl start_app &&
          rabbitmq-plugins enable rabbitmq_federation
          tail -f /dev/null
        "
    networks:
      - rabbitmq_net

  rabbit-3:
    image: rabbitmq:3-management
    container_name: rabbit-3
    hostname: rabbit-3
    ports:
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    command: >
        sh -c "
          rabbitmq-server -detached &&
          sleep 10 &&
          rabbitmqctl stop_app &&
          rabbitmqctl reset &&
          rabbitmqctl join_cluster rabbit@rabbit-1 &&
          rabbitmqctl start_app &&
          rabbitmq-plugins enable rabbitmq_federation
          tail -f /dev/null
        "
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
