services:
  rabbit-1-disc:
    image: rabbitmq:3-management
    container_name: rabbit-1-disc
    hostname: rabbit-1-disc
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_NODENAME: rabbit@rabbit-1-disc
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-1-ram:
    image: rabbitmq:3-management
    container_name: rabbit-1-ram
    hostname: rabbit-1-ram
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-1-ram
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_2:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-2-disc:
    image: rabbitmq:3-management
    container_name: rabbit-2-disc
    hostname: rabbit-2-disc
    ports:
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-2-disc
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_3:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-2-ram:
    image: rabbitmq:3-management
    container_name: rabbit-2-ram
    hostname: rabbit-2-ram
    ports:
      - "15675:15672"
      - "5675:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-2-ram
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_4:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-3-disc:
    image: rabbitmq:3-management
    container_name: rabbit-3-disc
    hostname: rabbit-3-disc
    ports:
      - "15676:15672"
      - "5676:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-3-disc
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_5:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  rabbit-3-ram:
    image: rabbitmq:3-management
    container_name: rabbit-3-ram
    hostname: rabbit-3-ram
    ports:
      - "15677:15672"
      - "5677:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-3-ram
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    networks:
      - rabbitmq_net
    volumes:
      - rabbit_6:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  rabbitmq_net:
    driver: bridge

volumes:
  rabbit_1:
  rabbit_2:
  rabbit_3:
  rabbit_4:
  rabbit_5:
  rabbit_6: