services:
  rabbit-1:
    image: rabbitmq:3-management
    container_name: rabbit-1
    hostname: rabbit-1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
      RABBITMQ_NODENAME: rabbit@rabbit-1
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbit_1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-2:
    image: rabbitmq:3-management
    container_name: rabbit-2
    hostname: rabbit-2
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-2
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    volumes:
      - rabbit_2:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  rabbit-3:
    image: rabbitmq:3-management
    container_name: rabbit-3
    hostname: rabbit-3
    ports:
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbit-3
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_ERLANG_COOKIE: "GKVOSIWUJDMEPWLGTSMV"
    volumes:
      - rabbit_3:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  rabbit_1:
  rabbit_2:
  rabbit_3: